[package]
name = "media-web"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
futures-channel = "=0.3.34"
js-sys.workspace = true
media-core.workspace = true
media-gpu.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "Document", "DomException", "File", "FileList", "Gpu", "HtmlCanvasElement",
    "HtmlInputElement", "Location", "Navigator", "VideoFrame", "VideoFrameInit", "Window",
] }
wgpu.workspace = true
